### ISSUE TITLE
切换角色后音画不一致

### ISSUE THREAD

**Issue by Etoice** [Canyu-Liu/objection#1]
软件版本：2.0
复现过程：
当使用具有三种台词的角色（如「绫里千寻」「成步堂龙一」或「御剑怜侍」）时，将台词设置为“等等”或者“看招”，然后切换到只有一种台词的角色（如「狩魔豪」「狩魔冥」以及「ゴドー」）
此时由于上述角色仅有“异议”一种台词，故台词会被强制设置为“异议”。接下来在主界面触发一次效果，会发现音频已经是“异议”，然而对话气泡却仍然是“等等”或者“看招”。

**Comment by Canyu-Liu** [comment]
感谢反馈，此问题已在2.1版本修复
